/*
 * pico sdk config autogen header stub for waf builds
 * normally auto-generated by cmake
 *
 * date: 2026-03-02
 */

// board definition (pico 2)
#include "boards/pico2.h"

// CMSIS exception renaming is handled by the include path
// the cmake build includes cmsis/rename_exceptions.h but we
// skip it here since the waf build doesn't use the CMSIS stubs
// in the same way. the rename_exceptions.h just maps IRQ names
// which aren't referenced in ArduPilot code directly.
