/*
 * pico sdk version header stub for waf builds
 * normally auto-generated by cmake
 *
 * date: 2026-03-02
 */
#ifndef _PICO_VERSION_H
#define _PICO_VERSION_H

#define PICO_SDK_VERSION_MAJOR    2
#define PICO_SDK_VERSION_MINOR    2
#define PICO_SDK_VERSION_REVISION 0
#define PICO_SDK_VERSION_STRING   "2.2.0"

#endif
